// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtB3i5yQE-drBK4WmegIZ57nr6I3EkuIA',
    appId: '1:256367464622:web:740233a5b51b078e399d3f',
    messagingSenderId: '256367464622',
    projectId: 'ele-safe',
    authDomain: 'ele-safe.firebaseapp.com',
    databaseURL: 'https://ele-safe-default-rtdb.firebaseio.com',
    storageBucket: 'ele-safe.firebasestorage.app',
    measurementId: 'G-C5L0MPC3J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD37EWfaXY8DBnYS2YTlq_fcc_uxcGL7jM',
    appId: '1:256367464622:android:422606de22eb1790399d3f',
    messagingSenderId: '256367464622',
    projectId: 'ele-safe',
    databaseURL: 'https://ele-safe-default-rtdb.firebaseio.com',
    storageBucket: 'ele-safe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLfv3myFaqYFtooGxrQU_vL43cVma57Dk',
    appId: '1:256367464622:ios:d7ea26002fe7b639399d3f',
    messagingSenderId: '256367464622',
    projectId: 'ele-safe',
    databaseURL: 'https://ele-safe-default-rtdb.firebaseio.com',
    storageBucket: 'ele-safe.firebasestorage.app',
    iosBundleId: 'com.example.elesafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLfv3myFaqYFtooGxrQU_vL43cVma57Dk',
    appId: '1:256367464622:ios:d7ea26002fe7b639399d3f',
    messagingSenderId: '256367464622',
    projectId: 'ele-safe',
    databaseURL: 'https://ele-safe-default-rtdb.firebaseio.com',
    storageBucket: 'ele-safe.firebasestorage.app',
    iosBundleId: 'com.example.elesafeApp',
  );
}
